In [45]:
import pandas as pd
import numpy as np
from sklearn.datasets import load_iris

In [46]:
dataset=load_iris()

In [48]:
print(dataset.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

In [49]:
dataset.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [52]:
df=pd.DataFrame(dataset.data, columns=d.feature_names)

In [53]:
df['target']=dataset.target

In [54]:
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  
0       0  
1       0  
2       0  
3       0  
4       0

In [55]:
df['target'].unique()

array([0, 1, 2])

In [56]:
df_copy=df[df['target']!=2]

In [57]:
df_copy['target'].unique()

array([0, 1])

In [78]:
from sklearn.model_selection import train_test_split

In [79]:
x = df_copy.drop(['target'], axis=1)  #df_copy.iloc[:,:-1]
y = df_copy[['target']]               #df_copy.iloc[:,-1]   

In [80]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.20, random_state=42)

In [81]:
from sklearn.linear_model import LogisticRegression

In [85]:
classification=LogisticRegression(max_iter=200)

In [86]:
classification

LogisticRegression(max_iter=200)

In [87]:
classification.fit(x_train,y_train)

C:\Users\pranj\anaconda3\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LogisticRegression(max_iter=200)

In [88]:
y_pred = classification.predict(x_test)

In [89]:
y_pred

array([1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0])

# Confusion Matrix, Accuracy, Classification Report

In [90]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

In [91]:
print(confusion_matrix(y_test,y_pred))

[[12  0]
 [ 0  8]]


In [92]:
print(accuracy_score(y_test,y_pred))

1.0


In [93]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        12
           1       1.00      1.00      1.00         8

    accuracy                           1.00        20
   macro avg       1.00      1.00      1.00        20
weighted avg       1.00      1.00      1.00        20



# Cross Validation

In [94]:
from sklearn.model_selection import KFold

In [95]:
cv=KFold(n_splits=5)

In [98]:
from sklearn.model_selection import cross_val_score

In [101]:
scores=cross_val_score(classification, x_train,y_train,scoring='accuracy',cv=cv)

C:\Users\pranj\anaconda3\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\pranj\anaconda3\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\pranj\anaconda3\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\pranj\anaconda3\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), 

In [102]:
scores

array([1., 1., 1., 1., 1.])

In [103]:
np.mean(scores)

1.0

# More complex data

In [113]:
from sklearn.datasets import make_classification
from sklearn.linear_model import LogisticRegression
x, y = make_classification(n_samples=1000, n_features=10, n_informative=5, n_redundant=5, n_classes=2, random_state=1)

In [114]:
from sklearn.model_selection import train_test_split

In [115]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.20, random_state=42)

In [116]:
from sklearn.linear_model import LogisticRegression

In [117]:
complex_class = LogisticRegression(max_iter=200)

In [118]:
complex_class

LogisticRegression(max_iter=200)

In [119]:
complex_class.fit(x_train,y_train)

LogisticRegression(max_iter=200)

In [121]:
y_pred = complex_class.predict(x_test)

In [122]:
y_pred

array([0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0,
       0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0,
       1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1,
       0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1,
       0, 1])

In [123]:
print(confusion_matrix(y_test,y_pred))

[[78 13]
 [29 80]]


In [124]:
print(accuracy_score(y_test,y_pred))

0.79


In [125]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.73      0.86      0.79        91
           1       0.86      0.73      0.79       109

    accuracy                           0.79       200
   macro avg       0.79      0.80      0.79       200
weighted avg       0.80      0.79      0.79       200



In [126]:
cv= KFold(n_splits=5)

In [127]:
cross_val_score(complex_class,x_train,y_train, cv=cv )

array([0.80625, 0.78125, 0.79375, 0.8125 , 0.85625])

In [128]:
np.mean(cross_val_score(complex_class,x_train,y_train, cv=cv ))

0.8099999999999999