In [1]:
import numpy as np

In [2]:
list(range(5))

[0, 1, 2, 3, 4]

In [4]:
list(range(1,11))

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [7]:
list(np.arange(.4,5.4, .2))

[0.4,
 0.6000000000000001,
 0.8000000000000002,
 1.0000000000000002,
 1.2000000000000002,
 1.4000000000000004,
 1.6000000000000005,
 1.8000000000000003,
 2.0000000000000004,
 2.2000000000000006,
 2.400000000000001,
 2.6000000000000005,
 2.8000000000000007,
 3.000000000000001,
 3.2000000000000006,
 3.400000000000001,
 3.600000000000001,
 3.800000000000001,
 4.000000000000002,
 4.200000000000001,
 4.400000000000002,
 4.600000000000001,
 4.800000000000002,
 5.000000000000002,
 5.200000000000002]

In [8]:
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [9]:
np.logspace(1,5,10)

array([1.00000000e+01, 2.78255940e+01, 7.74263683e+01, 2.15443469e+02,
       5.99484250e+02, 1.66810054e+03, 4.64158883e+03, 1.29154967e+04,
       3.59381366e+04, 1.00000000e+05])

In [10]:
np.logspace(1,5,10, base=2)

array([ 2.        ,  2.72158   ,  3.70349885,  5.0396842 ,  6.85795186,
        9.33223232, 12.69920842, 17.28095582, 23.51575188, 32.        ])

In [11]:
np.zeros(3)

array([0., 0., 0.])

In [12]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [13]:
np.zeros((2,3,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [14]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [18]:
arr = np.ones((2,3))

In [19]:
arr+2

array([[3., 3., 3.],
       [3., 3., 3.]])

In [20]:
arr*5

array([[5., 5., 5.],
       [5., 5., 5.]])

In [21]:
np.empty((2,3))

array([[5., 5., 5.],
       [5., 5., 5.]])

In [24]:
arr1 = np.eye(3)

In [25]:
arr1

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [26]:
import pandas as pd

In [27]:
pd.DataFrame(arr1)

0    1    2
0  1.0  0.0  0.0
1  0.0  1.0  0.0
2  0.0  0.0  1.0

In [28]:
np.random.rand(2,3)

array([[4.17902108e-04, 9.05749161e-01, 9.81718115e-01],
       [8.80569346e-01, 3.15677298e-01, 2.82030227e-01]])

In [29]:
np.random.rand(2,3)

array([[0.05233579, 0.14966693, 0.47304346],
       [0.76697385, 0.05308761, 0.85117254]])

In [31]:
np.random.randn(2,3)   # Mean=0, Std=1

array([[ 0.77086257,  0.64502154, -0.86469626],
       [-1.00778523, -0.55497124,  1.00701893]])

In [34]:
arr2 = np.random.randint(2,6, (4,4))

In [35]:
arr2.size

16

In [36]:
arr2.shape

(4, 4)

In [38]:
arr2.reshape(8,2)

array([[2, 4],
       [3, 2],
       [3, 2],
       [2, 5],
       [3, 5],
       [4, 3],
       [4, 5],
       [4, 4]])

In [39]:
arr2.reshape(2,2,4)

array([[[2, 4, 3, 2],
        [3, 2, 2, 5]],

       [[3, 5, 4, 3],
        [4, 5, 4, 4]]])

In [41]:
arr3 = np.random.randint(1,10, (3,4))

In [42]:
arr3

array([[1, 9, 3, 9],
       [6, 1, 7, 3],
       [1, 7, 8, 6]])

In [45]:
arr3<8

array([[ True, False,  True, False],
       [ True,  True,  True,  True],
       [ True,  True, False,  True]])

In [47]:
arr3[arr3>8]

array([9, 9])

In [50]:
arr3[0,[0,2]]

array([1, 3])

In [51]:
arr3[1:3,[2,3]]

array([[7, 3],
       [8, 6]])

In [52]:
arr4 = np.random.randint(1,5, (3,3))

In [53]:
arr5 = np.random.randint(1,5, (3,3))

In [55]:
arr4

array([[1, 2, 3],
       [1, 2, 4],
       [1, 4, 3]])

In [56]:
arr5

array([[4, 2, 3],
       [3, 3, 3],
       [4, 2, 1]])

In [54]:
arr4+arr5

array([[5, 4, 6],
       [4, 5, 7],
       [5, 6, 4]])

In [57]:
arr4-arr5

array([[-3,  0,  0],
       [-2, -1,  1],
       [-3,  2,  2]])

In [59]:
arr4*arr5   #Normal index multiplication

array([[ 4,  4,  9],
       [ 3,  6, 12],
       [ 4,  8,  3]])

In [61]:
arr4@arr5   #Matrux Multiplication

array([[22, 14, 12],
       [26, 16, 13],
       [28, 20, 18]])

In [62]:
arr6 = np.zeros((2,3))

In [63]:
arr6

array([[0., 0., 0.],
       [0., 0., 0.]])

In [64]:
arr6+5

array([[5., 5., 5.],
       [5., 5., 5.]])

In [68]:
a=np.array([1,2,3])

In [69]:
a

array([1, 2, 3])

In [70]:
arr6+a

array([[1., 2., 3.],
       [1., 2., 3.]])

In [75]:
b=np.array([[2,3]])

In [77]:
c = arr6+b.T

In [78]:
np.sqrt(c)

array([[1.41421356, 1.41421356, 1.41421356],
       [1.73205081, 1.73205081, 1.73205081]])

In [79]:
np.log10(c)

array([[0.30103   , 0.30103   , 0.30103   ],
       [0.47712125, 0.47712125, 0.47712125]])

In [80]:
np.exp(c)

array([[ 7.3890561 ,  7.3890561 ,  7.3890561 ],
       [20.08553692, 20.08553692, 20.08553692]])

In [81]:
np.min(c)

2.0

In [82]:
np.max(c)

3.0