In [1]:
import numpy as np

In [3]:
arr = np.array([1,2,3,4,5,6,7])

In [4]:
arr

array([1, 2, 3, 4, 5, 6, 7])

In [5]:
arr.sort()

In [6]:
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7])

In [16]:
arr1 = np.array([2,5,7,9,1,2,5,4,7,8,1,5])

In [17]:
arr1.sort()

In [18]:
np.sort(arr1)

array([1, 1, 2, 2, 4, 5, 5, 5, 7, 7, 8, 9])

In [19]:
np.searchsorted(arr1, 6)

8

In [35]:
arr2 = np.array([98,2,3,5,0,0,0,0,34,35,46,56])

In [36]:
np.count_nonzero(arr2)

8

In [37]:
np.where(arr2>0)

(array([ 0,  1,  2,  3,  8,  9, 10, 11], dtype=int64),)

In [38]:
np.extract(arr2>2, arr1)

array([1, 2, 2, 7, 7, 8, 9])

In [39]:
arr2

array([98,  2,  3,  5,  0,  0,  0,  0, 34, 35, 46, 56])

In [40]:
arr

array([ 16777216,  33554432,  50331648,  67108864,  83886080, 100663296,
       117440512])

In [41]:
arr.byteswap(True)

array([1, 2, 3, 4, 5, 6, 7])

In [42]:
arr

array([1, 2, 3, 4, 5, 6, 7])

In [43]:
arr2

array([98,  2,  3,  5,  0,  0,  0,  0, 34, 35, 46, 56])

In [44]:
a=np.copy(arr2)

In [45]:
a

array([98,  2,  3,  5,  0,  0,  0,  0, 34, 35, 46, 56])

In [46]:
b=arr2.view()

In [47]:
b

array([98,  2,  3,  5,  0,  0,  0,  0, 34, 35, 46, 56])

In [48]:
import numpy.matlib as nm

In [49]:
nm.zeros(3)

matrix([[0., 0., 0.]])

In [51]:
nm.ones((3,4))

matrix([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [52]:
nm.eye(4)

matrix([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

In [53]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [58]:
arr5 = np.random.randint([[2,3], [4,5]])
arr6 = np.random.randint([[5,3], [2,5]])

In [59]:
arr5

array([[1, 1],
       [1, 3]])

In [60]:
arr6

array([[1, 2],
       [1, 4]])

In [61]:
np.dot(arr5, arr6)

array([[ 2,  6],
       [ 4, 14]])

In [62]:
arr5@arr6

array([[ 2,  6],
       [ 4, 14]])