In [1]:
import numpy as np

In [2]:
l = [1,2,3,4,5]

In [4]:
arr = np.array(l)

In [5]:
type(arr)

numpy.ndarray

In [6]:
np.asarray(l)

array([1, 2, 3, 4, 5])

In [10]:
arr1 = np.array([[1,2,3], [4,5,6]])

In [11]:
arr.ndim

1

In [12]:
arr1.ndim

2

In [13]:
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
mat = np.matrix(l)

In [16]:
np.asanyarray(l)

array([1, 2, 3, 4, 5])

In [17]:
np.asanyarray(mat)

matrix([[1, 2, 3, 4, 5]])

In [18]:
a = arr

In [19]:
a

array([1, 2, 3, 4, 5])

In [20]:
arr

array([1, 2, 3, 4, 5])

In [21]:
arr[0]=100

In [22]:
arr

array([100,   2,   3,   4,   5])

In [23]:
a

array([100,   2,   3,   4,   5])

In [24]:
b=np.copy(arr)

In [25]:
b

array([100,   2,   3,   4,   5])

In [26]:
b[0]=234

In [27]:
b

array([234,   2,   3,   4,   5])

In [28]:
arr

array([100,   2,   3,   4,   5])

In [29]:
np.fromfunction(lambda i,j: i==j, (3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [30]:
np.fromfunction(lambda i,j: i*j, (3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [32]:
list(i*i for i in range(5))

[0, 1, 4, 9, 16]

In [40]:
iterable = (i*i for i in range(5))

In [41]:
np.fromiter(iterable, float)

array([ 0.,  1.,  4.,  9., 16.])

In [42]:
np.fromstring('23 45 56', sep=' ')

array([23., 45., 56.])

In [43]:
arr.size

5

In [44]:
arr1.size

6

In [45]:
arr1.shape

(2, 3)

In [47]:
arr.dtype

dtype('int32')

In [48]:
arr1.dtype

dtype('int32')