In [1]:
import numpy as np

In [2]:
arr = np.random.randint(1,10, (4,4))

In [3]:
arr

array([[9, 7, 7, 9],
       [5, 2, 2, 9],
       [5, 5, 7, 2],
       [1, 9, 4, 6]])

In [5]:
arr.reshape(8,2)

array([[9, 7],
       [7, 9],
       [5, 2],
       [2, 9],
       [5, 5],
       [7, 2],
       [1, 9],
       [4, 6]])

In [7]:
arr.T

array([[9, 5, 5, 1],
       [7, 2, 5, 9],
       [7, 2, 7, 4],
       [9, 9, 2, 6]])

In [8]:
arr.flatten()

array([9, 7, 7, 9, 5, 2, 2, 9, 5, 5, 7, 2, 1, 9, 4, 6])

In [9]:
np.expand_dims(arr, axis=1)

array([[[9, 7, 7, 9]],

       [[5, 2, 2, 9]],

       [[5, 5, 7, 2]],

       [[1, 9, 4, 6]]])

In [10]:
np.expand_dims(arr, axis=0)

array([[[9, 7, 7, 9],
        [5, 2, 2, 9],
        [5, 5, 7, 2],
        [1, 9, 4, 6]]])

In [11]:
data = np.array([[1],[2],[3],[4]])

In [12]:
data

array([[1],
       [2],
       [3],
       [4]])

In [14]:
np.squeeze(data)

array([1, 2, 3, 4])

In [15]:
np.repeat(data, 2)

array([1, 1, 2, 2, 3, 3, 4, 4])

In [16]:
np.repeat(data, 3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4])

In [17]:
np.roll(data, 3)

array([[2],
       [3],
       [4],
       [1]])

In [18]:
np.roll(data, 2)

array([[3],
       [4],
       [1],
       [2]])

In [21]:
np.diag(np.array([1,2,3,4,5]))

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [22]:
arr1 = np.random.randint(1,10, (3,4))
arr2 = np.random.randint(1,10, (3,4))

In [23]:
arr1

array([[3, 7, 9, 1],
       [2, 2, 1, 8],
       [9, 9, 4, 4]])

In [24]:
arr2

array([[4, 4, 9, 3],
       [6, 2, 3, 6],
       [5, 7, 2, 5]])

In [25]:
arr1+arr2

array([[ 7, 11, 18,  4],
       [ 8,  4,  4, 14],
       [14, 16,  6,  9]])

In [26]:
arr1*arr2

array([[12, 28, 81,  3],
       [12,  4,  3, 48],
       [45, 63,  8, 20]])

In [27]:
~arr1

array([[ -4,  -8, -10,  -2],
       [ -3,  -3,  -2,  -9],
       [-10, -10,  -5,  -5]], dtype=int32)

In [28]:
arr3 = np.array(['pranjal', 'bhardwaj'])

In [31]:
np.char.upper(arr3)

array(['PRANJAL', 'BHARDWAJ'], dtype='<U8')

In [32]:
np.char.capitalize(arr3)

array(['Pranjal', 'Bhardwaj'], dtype='<U8')

In [33]:
np.char.title(arr3)

array(['Pranjal', 'Bhardwaj'], dtype='<U8')

In [34]:
arr1

array([[3, 7, 9, 1],
       [2, 2, 1, 8],
       [9, 9, 4, 4]])

In [35]:
np.sin(arr1)

array([[ 0.14112001,  0.6569866 ,  0.41211849,  0.84147098],
       [ 0.90929743,  0.90929743,  0.84147098,  0.98935825],
       [ 0.41211849,  0.41211849, -0.7568025 , -0.7568025 ]])

In [36]:
np.cos(arr1)

array([[-0.9899925 ,  0.75390225, -0.91113026,  0.54030231],
       [-0.41614684, -0.41614684,  0.54030231, -0.14550003],
       [-0.91113026, -0.91113026, -0.65364362, -0.65364362]])

In [37]:
np.tan(arr1)

array([[-0.14254654,  0.87144798, -0.45231566,  1.55740772],
       [-2.18503986, -2.18503986,  1.55740772, -6.79971146],
       [-0.45231566, -0.45231566,  1.15782128,  1.15782128]])

In [38]:
np.log10(arr1)

array([[0.47712125, 0.84509804, 0.95424251, 0.        ],
       [0.30103   , 0.30103   , 0.        , 0.90308999],
       [0.95424251, 0.95424251, 0.60205999, 0.60205999]])

In [39]:
np.exp(arr1)

array([[2.00855369e+01, 1.09663316e+03, 8.10308393e+03, 2.71828183e+00],
       [7.38905610e+00, 7.38905610e+00, 2.71828183e+00, 2.98095799e+03],
       [8.10308393e+03, 8.10308393e+03, 5.45981500e+01, 5.45981500e+01]])

In [40]:
np.power(arr1,2)

array([[ 9, 49, 81,  1],
       [ 4,  4,  1, 64],
       [81, 81, 16, 16]], dtype=int32)

In [41]:
np.mean(arr1)

4.916666666666667

In [42]:
np.median(arr1)

4.0

In [44]:
np.std(arr1)

3.121386800054674

In [45]:
np.var(arr1)

9.743055555555555

In [46]:
np.min(arr1)

1

In [47]:
np.max(arr1)

9

In [48]:
arr1

array([[3, 7, 9, 1],
       [2, 2, 1, 8],
       [9, 9, 4, 4]])

In [49]:
arr2

array([[4, 4, 9, 3],
       [6, 2, 3, 6],
       [5, 7, 2, 5]])

In [51]:
np.subtract(arr1,arr2)

array([[-1,  3,  0, -2],
       [-4,  0, -2,  2],
       [ 4,  2,  2, -1]])

In [52]:
np.multiply(arr1,arr2)

array([[12, 28, 81,  3],
       [12,  4,  3, 48],
       [45, 63,  8, 20]])

In [53]:
np.mod(arr1,arr2)

array([[3, 3, 0, 1],
       [2, 0, 1, 2],
       [4, 2, 0, 4]], dtype=int32)

In [54]:
np.power(arr1,arr2)

array([[       81,      2401, 387420489,         1],
       [       64,         4,         1,    262144],
       [    59049,   4782969,        16,      1024]], dtype=int32)

In [55]:
np.sqrt(arr2)

array([[2.        , 2.        , 3.        , 1.73205081],
       [2.44948974, 1.41421356, 1.73205081, 2.44948974],
       [2.23606798, 2.64575131, 1.41421356, 2.23606798]])

In [56]:
np.mean(arr1)

4.916666666666667